services:
  # FastAPIバックエンドサービス
  - type: web
    name: sailing-strategy-api
    runtime: python
    region: singapore  # お客様の主な利用地域に近いリージョンを選択
    buildCommand: |
      cd backend
      python3 fix_encoding.py
      pip install -r requirements.txt
    startCommand: |
      cd backend
      uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: DEBUG
        value: false
      - key: API_VERSION
        value: "0.1.0"
      - key: PROJECT_NAME
        value: "セーリング戦略分析システム"
      - key: API_V1_STR
        value: "/api/v1"
      - key: CORS_ORIGINS
        # VercelデプロイのURLとローカル開発用のURLを指定
        value: https://sailing-strategy-analyzer.vercel.app,http://localhost:3000
      - key: FRONTEND_URL
        value: https://sailing-strategy-analyzer.vercel.app
      - key: ENCODING
        value: utf-8
      - key: LOG_LEVEL
        value: INFO
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "60"
      - key: ALGORITHM
        value: HS256
      - key: DATABASE_URL
        # この変数はRenderダッシュボードで直接設定します
        sync: false
      - key: SUPABASE_URL
        # この変数はRenderダッシュボードで直接設定します
        sync: false
      - key: SUPABASE_KEY
        # この変数はRenderダッシュボードで直接設定します
        sync: false
      - key: SUPABASE_JWT_SECRET
        # この変数はRenderダッシュボードで直接設定します
        sync: false
      - key: SECRET_KEY
        # この変数はRenderダッシュボードで直接設定します
        sync: false
      - key: PORT
        value: 8000
