services:
  # FastAPIバックエンドサービス
  - type: web
    name: sailing-strategy-api
    runtime: python
    region: singapore  # お客様の主な利用地域に近いリージョンを選択
    buildCommand: |
      python3 -m pip install --upgrade pip setuptools wheel
      # プロジェクトルートのsailing_data_processorをインストール
      python3 -m pip install -e .
      cd backend
      python3 -m pip install -r requirements.txt
      # sailing_data_processorが正しくインストールされているか確認
      python3 -c "try: import sailing_data_processor; print(f'sailing_data_processor version: {sailing_data_processor.__version__}'); except ImportError as e: print(f'Error importing sailing_data_processor: {e}'); exit(1)"
      python3 fix_encoding.py
    startCommand: |
      cd backend
      python3 -m uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: DEBUG
        value: "false"
      - key: API_VERSION
        value: "0.1.0"
      - key: PROJECT_NAME
        value: "セーリング戦略分析システム"
      - key: API_V1_STR
        value: "/api/v1"
      - key: CORS_ORIGINS
        value: "https://sailing-strategy-analyzer.vercel.app,http://localhost:3000"
      - key: FRONTEND_URL
        value: "https://sailing-strategy-analyzer.vercel.app"
      - key: ENCODING
        value: "utf-8"
      - key: LOG_LEVEL
        value: "INFO"
      - key: PORT
        value: "8000"
      # 下記項目はRenderダッシュボードで直接設定
      # - key: DATABASE_URL
      # - key: SECRET_KEY
      # - key: SUPABASE_URL
      # - key: SUPABASE_KEY
      # - key: SUPABASE_JWT_SECRET
