services:
  # FastAPIバックエンドサービス
  - type: web
    name: sailing-analyzer-backend
    runtime: python
    region: singapore  # お客様の主な利用地域に近いリージョンを選択
    buildCommand: |
      cd backend
      pip install -r requirements.txt
    startCommand: |
      cd backend
      uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: DEBUG
        value: false
      - key: CORS_ORIGINS
        # VercelデプロイのURLとローカル開発用のURLを指定
        value: https://sailing-strategy-analyzer.vercel.app,http://localhost:3000
      - key: DATABASE_URL
        # この変数はRenderダッシュボードで直接設定します
        sync: false
      - key: SUPABASE_URL
        # この変数はRenderダッシュボードで直接設定します
        sync: false
      - key: SUPABASE_KEY
        # この変数はRenderダッシュボードで直接設定します
        sync: false
      - key: SUPABASE_JWT_SECRET
        # この変数はRenderダッシュボードで直接設定します
        sync: false
      - key: SECRET_KEY
        # この変数はRenderダッシュボードで直接設定します
        sync: false
      - key: PORT
        value: 8000
