name: Python Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
    
    - name: Debug - Check imports and modules
      run: |
        echo "=== Current working directory ==="
        pwd
        echo "=== Python path ==="
        python -c "import sys; print(sys.path)"
        echo "=== Test directory contents ==="
        ls -la tests/
        echo "=== sailing_data_processor directory contents ==="
        ls -la sailing_data_processor/
        echo "=== Check module imports ==="
        python -c "import sailing_data_processor"
        echo "Import successful"
        
    - name: Test with pytest (collect only - detailed)
      run: |
        echo "=== Detailed pytest collection with error information ==="
        python -m pytest --collect-only tests/ --ignore=tests/project/ -vv --tb=long -r A --capture=no --show-capture=no --maxfail=10 || echo "Test collection failed"
        
    - name: Show test collection errors with alternative approach
      if: failure()
      run: |
        echo "=== Collecting errors from individual test files ==="
        for test_file in tests/test_*.py; do
          if [[ -f "$test_file" ]]; then
            echo "Checking $test_file ..."
            python -m pytest --collect-only "$test_file" -vv --tb=long || echo "Error in $test_file"
          fi
        done

    - name: Test with pytest
      run: |
        python -m pytest --cov=sailing_data_processor tests/ -vv --ignore=tests/project/ --tb=long -r A --capture=no
    
    - name: Upload coverage report
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: false
