[server]
# Python 3.11を使用するよう指定（Python 3.12の互換性問題を避けるため）
pythonVersion = "3.11"

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#0078D7"
backgroundColor = "#F0F2F5"
secondaryBackgroundColor = "#E6E8EB"
textColor = "#262730"
